import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://uat-external-alb.adp-uat.aws.domgencloud.net/GTConnect/UnifiedAcceptor/FrameworkDesktop.Main/2?sso=false');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('awsintegration');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('automation0325');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('WIB Agent Profile').click();
  await page.getByRole('button', { name: 'Select' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('link', { name: 'Identify Customer' }).click();
  // await page.waitForSelector('[id$="_cctRenderURL"]', { state: 'visible' });
  // await page.locator('[id$="_cctRenderURL"]').contentFrame().getByText('- Please Select -').waitFor();
  await page.waitForTimeout(10000);
  await page.locator('[id$="_cctRenderURL"]').contentFrame().nth(1).getByText('- Please Select -').click();
  await page.locator('[id$="_cctRenderURL"]').contentFrame().nth(1).getByRole('option', { name: 'Whirlpool' }).click();
  await page.locator('[id$="_cctRenderURL"]').contentFrame().nth(1).getByTestId('input_surname').fill('ADPAlGCpDf');
  await page.locator('[id$="_cctRenderURL"]').contentFrame().nth(1).getByTestId('button_search').click();
  await page.locator('[id$="_cctRenderURL"]').contentFrame().nth(1).getByRole('gridcell', { name: '305 Prospect St, Wethersfield' }).dblclick();
  await page.getByRole('link', { name: 'Add Item' }).click();
  await page.waitForTimeout(10000);
  const registerIframe = page.frameLocator('iframe[id*="_cctRenderURL"][src*="plans/new"]')
  await registerIframe.locator('[data-testid=button_registrationNextButton]').click();

  // await page.locator('[id$="_cctRenderURL"][src$="plans/new"]').contentFrame().getByTestId('button_registrationNextButton').click();
  await page.waitForTimeout(5000);
  await registerIframe.getByTestId('registrationCard.__ui__hasRegistrationCard_false').click();
  await page.waitForTimeout(2000);
  await registerIframe.getByRole('combobox', { name: '- Please Select -' }).first().click();
  await registerIframe.getByRole('option', { name: 'Whirlpool' }).click();
  await registerIframe.getByRole('combobox', { name: '- Please Select -' }).nth(1).click();
  await registerIframe.getByRole('option', { name: 'Cooktop' }).click();
  // await registerIframe.getByTestId('input_purchase.date').click();
  await registerIframe.getByTestId('input_purchase.date').fill('12/12/2024');
  // await registerIframe.getByTestId('input_purchase.price').click();
  await registerIframe.getByTestId('input_purchase.price').fill('500');
  await registerIframe.getByRole('combobox', { name: 'Search for a model (min. 3' }).click();
  await registerIframe.getByRole('combobox', { name: 'Search for a model (min. 3' }).fill('model123');
  // await registerIframe.getByTestId('input_serialNumber').click();
  await registerIframe.getByTestId('input_serialNumber').fill('serial123');
  await registerIframe.getByTestId('additionalDetails.operationalStatusCode_true').click();
  await registerIframe.getByText('Is the item in good working order?YesNo').click();
  await registerIframe.getByTestId('additionalDetails.extendedServicePlanOnAppliance_false').click();
  await registerIframe.getByTestId('button_address-capture-toggle').click();
  await registerIframe.getByTestId('address-menu-item').click();
  await registerIframe.getByTestId('button_add-item').click();
  await page.waitForTimeout(10000);
  await registerIframe.getByTestId('button_save').click();
  await page.waitForTimeout(5000);
  await registerIframe.getByRole('checkbox', { name: 'Select row' }).check();
  await registerIframe.getByTestId('button_next').click();
  await page.waitForTimeout(5000);
  await registerIframe.getByTestId('button_save').click();
  await page.waitForTimeout(5000);
  await registerIframe.getByTestId('button_next').click();
  await page.waitForTimeout(5000);
  await registerIframe.getByRole('row', { name: 'Cooktop Whirlpool Appliance' }).getByLabel('Select row').check();
  await registerIframe.getByTestId('button_save').click();
  await page.waitForTimeout(5000);
  await registerIframe.getByTestId('account.__ui__isSavedBillingAccount_N').click();
  await registerIframe.getByTestId('account.payment.methodType_ACH').click();
  await registerIframe.getByTestId('button_address-capture-toggle').click();
  await page.waitForTimeout(2000);
  await registerIframe.getByTestId('address-menu-item').click();
  await registerIframe.getByTestId('button_next').click();
  await page.waitForTimeout(10000);
  await registerIframe.getByText('- Select Account Type -').click();
  await registerIframe.getByRole('option', { name: 'Savings' }).click();
  await registerIframe.getByTestId('input_accountHolder').click();
  await registerIframe.getByTestId('input_accountHolder').fill('Acc New');
  await registerIframe.getByTestId('input_accountNo').click();
  await registerIframe.getByTestId('input_accountNo').fill('1221050896');
  await registerIframe.getByTestId('input_routingNumber').click();
  await registerIframe.getByTestId('input_routingNumber').fill('122105155');
  await registerIframe.getByTestId('button_save').click();
  await page.waitForTimeout(20000);
    
});